name: Go CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy
        working-directory: app

      - name: Run tests
        run: go test ./...
        working-directory: app

      - name: Build
        run: go build -o app .
        working-directory: app

